### ISSUE TITLE
Support for other versions

### ISSUE THREAD

**Issue by ghost** [jwdeveloper/JW_Piano#12]
Hello, I would like if you could add support for older versions of Minecraft especially 1.8.9.
If you can not, it is fine as I understand some developers do not have the time to backport to older versions of Minecraft.

**Comment by jwdeveloper** [comment]
Hi, unfortunatelly all my plugins are build to support 1.17, 1.18, 1.19 and newer versions.

**Comment by jwdeveloper** [comment]
bdw good music taste 👍

**Comment by ghost** [comment]
Ah thank you, I love Ragtime & Classical music.
Also thank you for your support!

**Comment by ghost** [comment]
@jwdeveloper I was wondering if you could backport to **1.16.5** instead of 1.8.9?
but if not, it is fine.

**Comment by jwdeveloper** [comment]
Sorry to say but most of my code relays on spigot **1.17.1** so **1.16.5** is impossible to make

**Comment by ghost** [comment]
Ah okay, my bad.
Well, thank you for your help though.

All though, Is there any other Piano plugins like this one that has midi keyboard support?

**Comment by jwdeveloper** [comment]
I don't think so

**Comment by ghost** [comment]
Ah alright.
It's fine, but again thanks!
