### ISSUE TITLE
Seems unable to connect from the application to minecraft

### ISSUE THREAD

**Issue by BiggieCheese64** [jwdeveloper/JW_Piano#3]
I love the concept of this and would love to use my midi keyboard to play a piano in minecraft, such a cool idea.

When I try to connect the website either will not state anything or that it cannot connect to the server.

This is a public server, that I am hosting through minecraft hosting service - Pebblehost.

![image](https://user-images.githubusercontent.com/34893466/180270845-b582f057-c0e9-4f1c-87ea-80e30de23a13.png)

**Comment by jwdeveloper** [comment]
Issue was caused because of not open port at the hosting panel
